### ISSUE TITLE
Mac版点Dock图标就会切换下一个，隐藏功能？

### ISSUE THREAD

**Issue by wonderffee** [lujqme/douyin#1]
RT
另外，没有评论还是没有看抖音app那种感觉啊

**Comment by wonderffee** [comment]
点下载时能不能不要每次都是download.mp4, 随机名字好一些，省得每次都要改名字

**Comment by lujqme** [comment]
- Mac点击dock切换这个算是bug，下个小版本修复一下。
- 会优先开发评论功能。
- 下载文件名这个也会改善。
