### ISSUE TITLE
抖音api

### ISSUE THREAD

**Issue by huanglizhuo** [lujqme/douyin#2]
hello 代码里通过 https://dy.lujianqiang.com/ 去获取的视频页，想知道你是如何解析抖音api 的，这部分代码会开源吗？

**Comment by lujqme** [comment]
整理下开源。

**Comment by huanglizhuo** [comment]
👍👍👍

**Comment by huanglizhuo** [comment]
我抓包抖音iOS版feed api 最后这个mas与as参数 感觉应该是抖音api加密用的，你后端是用feed api请求获取视频的吗？能将如何构造这两个参数代码开源吗？
mas=004eaa627662a568f2aa929ec8a2850e3df827dcf0b85be8c66ebe&as=a1856883e4146baa901705&ts=1529907780

**Comment by lujqme** [comment]
@huanglizhuo 我没有iOS设备，印象中mas这个是没用的，安卓版的接口参数有效的是as和cp，其算法在今日头条官网可以从公开的js中找到，我已经加到了README中。

**Comment by huanglizhuo** [comment]
thanks a lot @lujqme

**Comment by mirrorhanyu** [comment]
请教下算法中，i=(0,o.default)(t).toString().toUpperCase() 中的 o.default 如何获取？
