### ISSUE TITLE
修复

### ISSUE THREAD

**Issue by gclm** [lujqme/douyin#3]
![image](https://user-images.githubusercontent.com/27618687/41848888-a5c47714-78b1-11e8-9b19-70fa27b0d4c3.png)

连续刷新两个会出现这个问题 ，望大佬更新一下

macos 版的

**Comment by lujqme** [comment]
其实我自己这边也有这个问题。大概是因为服务器响应慢导致触发axios的默认超时，下一小版本把默认超时设置调稍微大一些，应该能解决这个问题。

感谢反馈～

**Comment by lujqme** [comment]
v0.2.1已经解决
