### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by joeaaa** [lujqme/douyin#6]
Got err when press arrowDown key...
TypeError: Cannot read property '1' of null
Some times, is no longer able to the next clip after this err appears, some times, I can still fetch the next clip.

![qq 20180714103251](https://user-images.githubusercontent.com/29770940/42719964-7864293c-8751-11e8-9cb9-fe7c3c20e39d.png)

**Comment by lujqme** [comment]
Thank you for reporting it.
This error will occur when the program can't able to parse the expected field that returned by the amemv website.
I'll try to cover all the case found.
